spring.application.name=autoloc-api

# Connexion a la base de donnees
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123


# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logs
logging.level.org.hibernate.SQL=OFF
logging.level.tn.esprit.autoloc=INFO

server.port=8081